name: Test
on:
  push:
    branches: [master, develop, main]
  pull_request:
    branches: [master, develop, main]

jobs:
  test:
    strategy:
      matrix:
        rust: [stable, "1.70"]
        os: [ubuntu-latest]
        include:
          - rust: stable
            os: macos-latest
          - rust: stable
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test
      - run: cargo test --features serde
        if: matrix.rust == 'stable'

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: cargo llvm-cov --features serde --lcov --output-path lcov.info
      - uses: codecov/codecov-action@v4
        with:
          files: lcov.info
